service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  handler:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
